### PR TITLE
Meta and household

### PR DESCRIPTION
**Pull request by GregMagnat**
adding meta tags especially for SEO and some modifications like the banner where I had a dimension problem !

### CODE REVIEW

**Comment by cypradoux** [comment]
Nice job on meta but what are changes on yarn.lock @GregMagnat ?

**Comment by cypradoux** [comment]
Thanks for job Gregory, but we need to correct @bicycle.name by @bicycle.model in meta description for bicycle show view.
Moreover, why are there this changes in yarn.lock?
Thank you!

**Comment by masechkacat** [comment]
pas d'inquetude pour yarn.lock (apparament ca vien de notre branche d'equipe) yarn.lock se build  a la base de yarn
le balise doubles a corrige - sinon pour les styles - j'ai les completment changer (sur page index) donc prends pas la tete

**Comment by GregMagnat** [comment]
All conflict is ok !

**Review by ikramiste — APPROVED** [review]

**Review by cypradoux — APPROVED** [review]

**Pull request merged**
