### PR TITLE
Fix error calendar conflict, Add icons and fix some details

### PR DESCRIPTION
**Pull request by cypradoux**
# Fixing error with render calendar due to conflit merging

# Calendar responsivity by Sylvain
- Calendar is now responsive for mobile

# Add user & bike icon when users didn't download it
- Add user icon in user show when the user didn't add an avatar : 
image

- Add bike icon associate to bicycle add when the user didn't download any bike image :
image

image

# Translating in french
- Translate alerts messages in controller from english to french (bicycle, user, review)

# Show green notice alert when "positive" alert (log in, sign in ...)
- Keep red alert for destroy
- But I need to find where can I change notice alert for session (log out)
image

# Lilian's request
- Price button switch to label in show bicycle
- Hide owner's email in show bicycle and put first_name & last_name
- Add stars in log in form and new bicycle form to show which input must be complete
- Wrapped list in show user by < ul >
- Do not show entire address in show bicycle but only country, city, postal code
- Fix problem for button "Je cherche un vélo" on navbar
- Add "alt" which was missing for image in show bicycle

# Accessories
- Add dropdown but need to be adjusted when model will be ready
- Can't fix saving accessories when creating new bicycle add

### CODE REVIEW

**Review by masechkacat — APPROVED** [review]

**Comment by ikramiste** [comment]
I see a lot of changes since the last approval, cannot wait to see your readme to see what has been added! Looking forward to some explanations regarding the different changes in controllers. 😄

**Comment by cypradoux** [comment]
Readme is ready to be read @ikramiste :)

**Comment by ikramiste** [comment]
Hi! @cypradoux 😄 

_________________

I resolved some conflicts via github but please double check on your end (without erasing @GregMagnat or @ikramiste contributions, please keep both changes as those conflicts were OK to cohabit).
Kind reminder that it's important to test locally before confirming something is functional. 👍 

_________________

Once it's done, I will happily provide an approval for the merge. 💯

**Comment by cypradoux** [comment]
@ikramiste it's okay for me you everything is working !

**Review by ikramiste — APPROVED** [review]
Ok on my end for merge - will try this in production! 👌

**Pull request merged**
